name: learn-github-actions
on: 
  workflow_dispatch:
    inputs:
      app:
        description: 'what? vfaserver | mms | sc | vfaadmin'
        required: true
        default: 'vfaserver'
      environment:
        description: 'where? staging | staging2 | preprod | production'
        required: true
        default: 'staging'
      branch:
        description: 'branch? (optional, defaults at RailsDeployer/deploys.yml)'
jobs:
  check-bats-version:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
